### ISSUE TITLE
var-button 点击边框出现红线

### ISSUE THREAD

**Issue by scallopsF** [varletjs/varlet#1628]
# About `styles` 🛠️
<img width="381" alt="image" src="https://github.com/varletjs/varlet/assets/74759442/a08df636-c5e4-4cc7-bfba-5757e9f4e19a">
<img width="411" alt="image" src="https://github.com/varletjs/varlet/assets/74759442/b05411d1-1ee6-43a7-ab76-6c22c80272b2">
<img width="589" alt="image" src="https://github.com/varletjs/varlet/assets/74759442/228602b4-29ca-4969-80d7-b2107795571a">

**点击任何一个按钮后，都会出现一个红色边框，我这是刚建的vue3框架，使用的var-button。代码如下**
``` javascript
<template>
  <div>
    <var-button type="primary">主要按钮</var-button>
    <var-button text outline type="primary">外边框按钮</var-button>
    <var-button text type="primary">纯文字按钮</var-button>
  </div>
</template>
```

**Comment by scallopsF** [comment]
`
<template>
  <div>
    <var-button type="primary">主要按钮</var-button>
    <var-button text outline type="primary">外边框按钮</var-button>
    <var-button text type="primary">纯文字按钮</var-button>
  </div>
</template>
`
上面的代码错了 看这个

**Comment by scallopsF** [comment]
<var-button type="primary">主要按钮</var-button>
    <var-button text outline type="primary">外边框按钮</var-button>
    <var-button text type="primary">纯文字按钮</var-button>
    这个是代码

**Comment by scallopsF** [comment]
```javascript
<var-button type="primary">主要按钮</var-button>
<var-button text outline type="primary">外边框按钮</var-button>
<var-button text type="primary">纯文字按钮</var-button>
```
这个是代码

**Comment by scallopsF** [comment]
```css

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}
button:hover {
  border-color: #646cff;
}
button:focus,
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}
```
vue3自带的全局样式 删除了就可以了
