### ISSUE TITLE
VarCard切换主题

### ISSUE THREAD

**Issue by Luxcis** [varletjs/varlet#1887]
# About `styles` 🛠️

我使用VarCard切换主题时背景颜色无法切换，我已经根据文档注入了css
```css
body {
  transition: background-color .25s, color .25s;
  color: var(--color-text);
  background-color: var(--color-body);
  color-scheme: var(--color-scheme);
}
```
```html
<VarCard
  src="https://varletjs.org/cat.jpg"
  image-height="160"
  image-width="120"
  style="width: 120px"
>
  <template #title>
<var-ellipsis style="width: 120px"> 我表情悠哉 跳个大概 </var-ellipsis>
  </template>
</VarCard>
```

![Image](https://github.com/user-attachments/assets/9331ac53-b816-479a-9746-16b4d241e743)
