### ISSUE TITLE
引用字体时间过长问题

### ISSUE THREAD

**Issue by lucikehao** [varletjs/varlet#415]
- 发现总有网络请求非常长，未结束时不显示图标，链接是https://cdn.jsdelivr.net/npm/@varlet/icons/dist/fonts/varlet-icons-webfont.woff2，看了文档应该是因为图标是基于这个字体
- 能否给予某种方式指定字体文件链接或者自己打包而不用cdn呢，因为cdn总是抽风

**Comment by haoziqaq** [comment]
在近几个版本里，我们将字体移出了主包，主要考虑到我们扩展字体的时候会影响主包尺寸，并且也不利于浏览器缓存。

你可以先找到`node_modules/@varlet/icons/dist/css`，将它拷贝到项目里修改字体的引用地址使用，作为一个临时方案。
我们再找找更稳定的cdn

**Comment by haoziqaq** [comment]
还有一个方案，新建一个css写入如下内容然后引入到你的工程里

```css
@font-face {
  font-family: "varlet-icons";
  src: url("@varlet/icons/dist/fonts/varlet-icons-webfont.woff2") format("woff2"),
    url("@varlet/icons/dist/fonts/varlet-icons-webfont.woff") format("woff"),
    url("@varlet/icons/dist/fonts/varlet-icons-webfont.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```
